### ISSUE TITLE
Subdomains not working

### ISSUE THREAD

**Issue by monkevlar** [Zjjc123/doomscroll-blocker#2]
I think it would be cool to insert custom URLs as monitored domains, instead of solely checking the root domain. As an example, I often use LinkedIn to search posts, browse bookmarks, and read comments. It happens that I subconsciously head to the homepage (linkedin.com/feed/) and start doomscrolling. I would like to limit the blocker to the /feed/ subdomain, while allowing the scroll on other subdomains.

**Comment by jasonzh0** [comment]
great idea! will look into it. feel free to also open a PR as well
